import Head from "next/head";
import React from "react";
import { Player, PlayerRef } from "@remotion/player";
import { useEffect, useRef } from "react";
import { Message } from "../components/Message";
import NoSSR from "../components/index";

const Home: React.FC = () => {
  const playerRef = useRef<PlayerRef>(null);

  useEffect(() => {
    if (playerRef.current) {
      console.log(playerRef.current.getCurrentFrame());
    }
  }, []);

  return (
    <div>
      <Head>
        <title>Remotion + Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NoSSR>
          <Player
            ref={playerRef}
            component={Message}
            compositionWidth={1280}
            compositionHeight={720}
            controls
            durationInFrames={350}
            fps={30}
          ></Player>
        </NoSSR>
      </main>
    </div>
  );
};

export default Home;
